# Generated by Django 4.2.4 on 2023-08-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SleepPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('UP', 'Подьем'), ('DOWN', 'Отбой')], max_length=4, verbose_name='Событие')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Точка сна',
                'verbose_name_plural': 'Точки сна',
            },
        ),
    ]
